sudo: required
langauge: python
python:
  - '3.5'

services:
  - docker
  - postgresql

install:
  - sudo pip install -r requirements.txt

before_script:
  - docker-compose up --build -d
  - psql -c 'CREATE DATABASE travis_db;' -U postgres
  - python -V

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test

after_script:
  - docker-compose down

env:
  - DOCKER_COMPOSE_VERSION = 1.4.2

before_install:
  - docker --version
  - docker build -t $DOCKER_USERNAME/protrack:latest .
  - docker images
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ./docker-compose
  - sudo mv ./docker-compose /usr/bin/docker-compose
  - sudo chmod +x /usr/bin/docker-compose

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/protrack:latest

branches:
  only:
  - master
  - development
  - Project_init
  - Milestone_testing