version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    command: -p 8001
    volumes:
      - ./database:/var/lib/postgresql/data
  web:
#    build: .
    image: jkam/protrack:latest
    environment:
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
      - HTTP_PROXY=proxy.uns.ac.rs:8080
      - HTTPS_PROXY=proxy.uns.ac.rs:8080
#    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
