"""
Django settings for ProTrack project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v!_oz2+bo$f^%edb^#arfr3nb6o2vjx#t@o0+ur!hlbm&%oxa%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["0.0.0.0", "localhost", "147.91.177.194", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'projects.apps.ProjectsConfig',
    'issues.apps.IssuesConfig',
    'milestones.apps.MilestonesConfig',
    'organizations.apps.OrganizationsConfig',
    'activities.apps.ActivitiesConfig',
    'comments.apps.CommentsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'tinymce'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProTrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProTrack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
#
#

if 'TRAVIS' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'travis_db',
            'USER': 'postgres',
            'PASSWORD': '',
            'HOST': 'localhost',
            'PORT': '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'pro_track_db',
            'USER': 'root',
            'PASSWORD': 'root',
            'HOST': 'db',
            'PORT': 8001,
            # 'HOST': 'localhost',
            # 'PORT': 5432,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#django-richtextfield configuration
# 'js': ['//tinymce.cachefly.net/4.2/tinymce.min.js'],
    # 'init_template': 'djrichtextfield/init/tinymce.js',
    # 'settings': {
    #     'menubar': False,
    #     'statusbar': False,
    #     'plugins': 'link image code emoticons textcolor colorpicker lists',
    #     'toolbar': 'undo redo | styleselect | fontsizeselect | forecolor backcolor | emoticons |bold italic underline | numlist bullist | code link | removeformat',
    #     'width': '100%',
    #     'height': '25%'
    # }
#
# DJRICHTEXTFIELD_CONFIG = {
#     'js': ['//cdn.ckeditor.com/4.4.4/standard/ckeditor.js'],
#     'init_template': 'djrichtextfield/init/ckeditor.js',
#     'settings': {
#         'resize_enabled': False,
#         'label': False,
#         'removePlugins': 'elementspath',
#         'toolbar': [
#             {'items': ['Undo', 'Redo', '-', 'Format', '-', 'Bold', 'Italic', '-', 'NumberedList', 'BulletedList']}
#         ],
#         'height': '25%',
#         'width': '100%'
#
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

#email service
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'protrack.service@gmail.com'
EMAIL_HOST_PASSWORD = 'protrack'
EMAIL_PORT = 587

#login redirect
LOGIN_URL = 'core:sign_in'
LOGIN_REDIRECT_URL = 'core:home'