# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
