# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_auto_20180122_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(default='OPEN', max_length=8),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='total_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='total_time_spent',
            field=models.FloatField(default=0.0),
        ),
    ]
