# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_auto_20180122_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='test',
            field=models.DateField(null=True),
        ),
    ]
