# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0005_milestone_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='test',
        ),
    ]
