# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0006_remove_milestone_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
